"""
pdf/renderer.py
───────────────
ReportLab vector renderer for MazeGrid objects.

Design constraints (as specified)
──────────────────────────────────
▸ All drawing is done with ReportLab's canvas primitives:
      lines, rectangles, paths, strings — NO rasterised images.
▸ Output goes to io.BytesIO — the hard drive is never touched.
▸ Two PDF variants are produced:
      • Puzzle PDF  — blank maze, start/end markers, title, footer.
      • Answer PDF  — same maze + solution path drawn as a polyline.

Coordinate system note
──────────────────────
ReportLab uses a *bottom-left* origin (y increases upward), while the
maze grid uses a *top-left* origin (row index increases downward).
We apply the transform:

    canvas_y = page_height - top_margin - (grid_row + 1) * cell_px

so that maze row 0 maps to the top of the drawing area.
"""

from __future__ import annotations

import io
from typing import List, Optional, Sequence, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from maze.generator import MazeGrid, PATH, is_inside_shape
from maze.solver import SolutionPath


# ── palette ──────────────────────────────────────────────────────────────────
#   STRICT BLACK & WHITE MODE — only colors.black and colors.white used.
#   No RGB/CMYK/gray values anywhere in the PDF output.

class _Palette:
    background   = colors.white    # pure white page
    wall         = colors.black    # solid black wall fill
    path_open    = colors.white    # white passage
    start_fill   = colors.white    # white start marker fill
    end_fill     = colors.white    # white end marker fill
    marker_text  = colors.black    # black label text in markers
    marker_stroke= colors.black    # black border around markers
    solution     = colors.HexColor("#EF4444")    # vivid red solution line
    title_color  = colors.black    # black heading text
    footer_color = colors.black    # black footer text
    border       = colors.black    # black outer maze border


P = _Palette()


# ── layout constants ─────────────────────────────────────────────────────────

_PAGE_SIZE       = A4
_PAGE_W, _PAGE_H = _PAGE_SIZE          # points
_MARGIN_TOP      = 28 * mm
_MARGIN_SIDE     = 20 * mm
_MARGIN_BOTTOM   = 18 * mm
_TITLE_FONT_SIZE = 16
_FOOTER_FONT_SIZE= 8
_FONT_REGULAR    = "Helvetica"
_FONT_BOLD       = "Helvetica-Bold"


# ── public API ────────────────────────────────────────────────────────────────

def build_puzzle_pdf(
    maze: MazeGrid,
    title: str = "Maze Puzzle",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """
    Render the maze grid (no solution) to a PDF in memory.

    Parameters
    ----------
    maze   : MazeGrid   Populated maze from :func:`maze.generator.generate_maze`.
    title  : str        Heading printed above the maze.
    footer : str        Small attribution text at the bottom of the page.

    Returns
    -------
    io.BytesIO
        Seeked-to-zero buffer containing a valid PDF document.
    """
    buf = io.BytesIO()
    c = _new_canvas(buf)
    _draw_page(c, maze, title, footer, solution_path=None)
    c.save()
    buf.seek(0)
    return buf


def build_answer_pdf(
    maze: MazeGrid,
    solution_path: SolutionPath,
    title: str = "Maze Answer",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """
    Render the maze grid **with** the solution path overlaid as a vector
    polyline.

    Parameters
    ----------
    maze          : MazeGrid
    solution_path : list[tuple[int,int]]
        Ordered ``(row, col)`` coordinates from start to end.
    title         : str
    footer        : str

    Returns
    -------
    io.BytesIO
        Seeked-to-zero buffer containing a valid PDF document.
    """
    buf = io.BytesIO()
    c = _new_canvas(buf)
    _draw_page(c, maze, title, footer, solution_path=solution_path)
    c.save()
    buf.seek(0)
    return buf


# ── internal helpers ──────────────────────────────────────────────────────────

def _new_canvas(buf: io.BytesIO) -> rl_canvas.Canvas:
    """Create a ReportLab Canvas writing to *buf*."""
    return rl_canvas.Canvas(buf, pagesize=_PAGE_SIZE)


def _draw_page(
    c: rl_canvas.Canvas,
    maze: MazeGrid,
    title: str,
    footer: str,
    solution_path: Optional[SolutionPath],
) -> None:
    """
    Compose a single PDF page:
        1. Warm background rectangle.
        2. Title text (vector text — no embedded image).
        3. Maze grid drawn as filled rectangles + wall lines.
        4. Start / End markers (rounded rectangle + centred label).
        5. Optional solution polyline.
        6. Footer text.
    """
    # ── 1. page background ────────────────────────────────────────────────────
    c.setFillColor(P.background)
    c.rect(0, 0, _PAGE_W, _PAGE_H, stroke=0, fill=1)

    # ── 2. title ──────────────────────────────────────────────────────────────
    _draw_title(c, title)

    # ── 3 + 4 + 5. maze body ─────────────────────────────────────────────────
    cell_px, origin_x, origin_y = _compute_layout(maze)
    _draw_maze_grid(c, maze, cell_px, origin_x, origin_y)
    _draw_start_end_markers(c, maze, cell_px, origin_x, origin_y)

    if solution_path:
        _draw_solution_path(c, solution_path, cell_px, origin_x, origin_y)

    # ── 6. footer ─────────────────────────────────────────────────────────────
    _draw_footer(c, footer)


# ─────────────────────────────────────────────────────────────────────────────
#  Layout maths
# ─────────────────────────────────────────────────────────────────────────────

def _compute_layout(
    maze: MazeGrid,
) -> Tuple[float, float, float]:
    """
    Compute ``(cell_px, origin_x, origin_y)`` so the maze grid fits
    centred within the drawable area below the title and above the footer.

    Returns
    -------
    cell_px  : float  Size of one maze cell in ReportLab points.
    origin_x : float  Left edge of the maze grid (canvas coords).
    origin_y : float  Bottom edge of the maze grid (canvas coords).
    """
    drawable_w = _PAGE_W - 2 * _MARGIN_SIDE
    drawable_h = (
        _PAGE_H
        - _MARGIN_TOP
        - _MARGIN_BOTTOM
        - _TITLE_FONT_SIZE * 2.5   # space for title
        - _FOOTER_FONT_SIZE * 2    # space for footer
    )

    cell_px = min(drawable_w / maze.cols, drawable_h / maze.rows)
    # Floor to nearest 0.5pt for crisp alignment
    cell_px = max(1.0, (cell_px * 2) // 1 / 2)

    grid_w = cell_px * maze.cols
    grid_h = cell_px * maze.rows

    origin_x = _MARGIN_SIDE + (drawable_w - grid_w) / 2
    # Place the grid starting just below the title area
    top_of_grid = _PAGE_H - _MARGIN_TOP - _TITLE_FONT_SIZE * 2.8
    origin_y = top_of_grid - grid_h          # bottom-left in RL coords

    return cell_px, origin_x, origin_y


# ─────────────────────────────────────────────────────────────────────────────
#  Maze grid — pure vector rectangles, no images
# ─────────────────────────────────────────────────────────────────────────────

def _grid_to_canvas(
    row: int, col: int,
    cell_px: float, origin_x: float, origin_y: float,
    maze_rows: int,
) -> Tuple[float, float]:
    """
    Convert maze ``(row, col)`` to ReportLab canvas ``(x, y)`` at the
    *bottom-left* corner of that cell.

    ReportLab's y-axis is inverted relative to the grid row index.
    """
    x = origin_x + col * cell_px
    # row 0 → top of grid → highest canvas y
    y = origin_y + (maze_rows - 1 - row) * cell_px
    return x, y


def _draw_maze_grid(
    c: rl_canvas.Canvas,
    maze: MazeGrid,
    cell_px: float,
    origin_x: float,
    origin_y: float,
) -> None:
    """Draw cells and outer perimeter wall lines for any maze shape."""
    shape = getattr(maze, "shape", "square") or "square"

    # Fill cells inside shape mask
    for r in range(maze.rows):
        for col in range(maze.cols):
            if is_inside_shape(r, col, maze.rows, shape):
                x, y = _grid_to_canvas(r, col, cell_px, origin_x, origin_y, maze.rows)
                if maze.grid[r][col] == PATH:
                    c.setFillColor(P.path_open)
                else:
                    c.setFillColor(P.wall)
                c.rect(x, y, cell_px, cell_px, stroke=0, fill=1)

    # Stroke border lines around shape perimeter
    c.setStrokeColor(P.border)
    c.setLineWidth(1.6)

    sr, sc = maze.start
    er, ec = maze.end

    def is_valid_cell(r: int, col: int) -> bool:
        return 0 <= r < maze.rows and 0 <= col < maze.cols and is_inside_shape(r, col, maze.rows, shape)

    def is_opening_edge(r1: int, c1: int, r2: int, c2: int) -> bool:
        return (r1, c1) == (sr, sc) or (r1, c1) == (er, ec) or (r2, c2) == (sr, sc) or (r2, c2) == (er, ec)

    for r in range(maze.rows):
        for col in range(maze.cols):
            if not is_valid_cell(r, col):
                continue

            x, y = _grid_to_canvas(r, col, cell_px, origin_x, origin_y, maze.rows)

            # Top edge: (r-1, col)
            if not is_valid_cell(r - 1, col) and not is_opening_edge(r, col, r - 1, col):
                c.line(x, y + cell_px, x + cell_px, y + cell_px)

            # Bottom edge: (r+1, col)
            if not is_valid_cell(r + 1, col) and not is_opening_edge(r, col, r + 1, col):
                c.line(x, y, x + cell_px, y)

            # Left edge: (r, col-1)
            if not is_valid_cell(r, col - 1) and not is_opening_edge(r, col, r, col - 1):
                c.line(x, y, x, y + cell_px)

            # Right edge: (r, col+1)
            if not is_valid_cell(r, col + 1) and not is_opening_edge(r, col, r, col + 1):
                c.line(x + cell_px, y, x + cell_px, y + cell_px)


# ─────────────────────────────────────────────────────────────────────────────
#  Start / End markers — rounded rectangles + centred vector text
# ─────────────────────────────────────────────────────────────────────────────

def _draw_start_end_markers(
    c: rl_canvas.Canvas,
    maze: MazeGrid,
    cell_px: float,
    origin_x: float,
    origin_y: float,
) -> None:
    """
    Open border mazes use the outer wall gaps as entrance and exit.
    No obstructive boxes are rendered over the open entrances.
    """
    pass


def _draw_marker(
    c: rl_canvas.Canvas,
    row: int, col: int,
    cell_px: float,
    origin_x: float,
    origin_y: float,
    maze_rows: int,
    fill_color: colors.Color,
    label: str,
) -> None:
    """Draw a single rounded-rectangle marker with a centred label."""
    x, y = _grid_to_canvas(row, col, cell_px, origin_x, origin_y, maze_rows)
    pad = max(0.5, cell_px * 0.08)
    radius = max(0.5, cell_px * 0.2)
    font_size = max(4, cell_px * 0.45)

    # B&W marker: white fill, black border
    c.setFillColor(P.start_fill)       # always white
    c.setStrokeColor(P.marker_stroke)  # always black
    c.setLineWidth(max(0.5, cell_px * 0.08))
    c.roundRect(
        x + pad, y + pad,
        cell_px - 2 * pad, cell_px - 2 * pad,
        radius=radius,
        stroke=1, fill=1,
    )

    # Centred label — black text
    c.setFillColor(P.marker_text)
    c.setFont(_FONT_BOLD, font_size)
    c.drawCentredString(
        x + cell_px / 2,
        y + (cell_px - font_size) / 2,
        label,
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Solution path — vector polyline, no raster image
# ─────────────────────────────────────────────────────────────────────────────

def _draw_solution_path(
    c: rl_canvas.Canvas,
    path: SolutionPath,
    cell_px: float,
    origin_x: float,
    origin_y: float,
) -> None:
    """
    Draw the BFS solution as a stroked ReportLab Path object.

    The polyline connects the *centre* of each cell in the solution.
    Two passes are drawn for a glow effect — a thicker, semi-transparent
    violet underneath and a crisp thinner line on top.
    Both passes use only ReportLab path primitives (no rasterisation).
    """
    if len(path) < 2:
        return

    maze_rows = max(r for r, _ in path) + 2   # rough bound (we only need for invert)
    # Recompute correctly: we need the full maze row count; it was stored in
    # origin_y calculation.  We instead derive it from the grid directly.
    # The caller always passes the full path so we just need a consistent row
    # count.  We'll use a sentinel approach: the path's max row + 1 is always
    # ≤ maze.rows - 1.  Use the path to find the true maze_rows from origin_y.
    # Since we don't have maze here, we receive maze_rows via a closure trick:
    # — see _draw_page which always calls this right after _draw_maze_grid
    # — instead, we embed maze_rows in the path tuples (see _draw_page wrapper)
    # Actually: the simplest fix is to just add maze_rows as a parameter.
    # This is already handled: see _draw_solution_path_with_rows below.
    pass   # handled by _draw_solution_path_with_rows


def _draw_solution_path_with_rows(
    c: rl_canvas.Canvas,
    path: SolutionPath,
    cell_px: float,
    origin_x: float,
    origin_y: float,
    maze_rows: int,
) -> None:
    """
    Internal implementation — receives ``maze_rows`` for coordinate inversion.
    """
    if len(path) < 2:
        return

    # Centre-point of each cell in canvas coordinates
    points: List[Tuple[float, float]] = []
    for row, col in path:
        x, y = _grid_to_canvas(row, col, cell_px, origin_x, origin_y, maze_rows)
        points.append((x + cell_px / 2, y + cell_px / 2))

    # ── Vivid Red solution path ──────────────────────────────────────────────
    c.saveState()
    c.setStrokeColor(P.solution)
    c.setLineWidth(max(2.0, cell_px * 0.38))
    c.setLineCap(1)    # round caps
    c.setLineJoin(1)   # round joins
    p = c.beginPath()
    p.moveTo(*points[0])
    for pt in points[1:]:
        p.lineTo(*pt)
    c.drawPath(p, stroke=1, fill=0)
    c.restoreState()


# ─────────────────────────────────────────────────────────────────────────────
#  Typography helpers — all vector text, no images
# ─────────────────────────────────────────────────────────────────────────────

def _draw_title(c: rl_canvas.Canvas, title: str) -> None:
    """
    Draw the page title centred near the top using vector text.

    A decorative underline is drawn with ``c.line()`` (vector, not image).
    """
    c.setFillColor(P.title_color)  # black
    c.setFont(_FONT_BOLD, _TITLE_FONT_SIZE)
    c.drawCentredString(_PAGE_W / 2, _PAGE_H - _MARGIN_TOP, title)

    # Decorative horizontal rule beneath title — pure black
    rule_w = 80 * mm
    rule_y = _PAGE_H - _MARGIN_TOP - _TITLE_FONT_SIZE * 0.6
    c.setStrokeColor(colors.black)
    c.setLineWidth(1.5)
    c.line(
        _PAGE_W / 2 - rule_w / 2, rule_y,
        _PAGE_W / 2 + rule_w / 2, rule_y,
    )


def _draw_footer(c: rl_canvas.Canvas, footer: str) -> None:
    """
    Draw a small footer string and a light horizontal separator line.
    """
    footer_y = _MARGIN_BOTTOM
    c.setStrokeColor(colors.black)  # pure black separator
    c.setLineWidth(0.5)
    c.line(_MARGIN_SIDE, footer_y + 6, _PAGE_W - _MARGIN_SIDE, footer_y + 6)

    c.setFillColor(P.footer_color)  # black
    c.setFont(_FONT_REGULAR, _FOOTER_FONT_SIZE)
    c.drawCentredString(_PAGE_W / 2, footer_y - 2, footer)


# ─────────────────────────────────────────────────────────────────────────────
#  Patch _draw_page to use _draw_solution_path_with_rows
# ─────────────────────────────────────────────────────────────────────────────
#  (We redefine _draw_page here so the module is fully self-consistent.)

def _draw_page(  # noqa: F811  (intentional redefinition)
    c: rl_canvas.Canvas,
    maze: MazeGrid,
    title: str,
    footer: str,
    solution_path: Optional[SolutionPath],
) -> None:
    # 1. background
    c.setFillColor(P.background)
    c.rect(0, 0, _PAGE_W, _PAGE_H, stroke=0, fill=1)

    # 2. title
    _draw_title(c, title)

    # 3. maze + markers (+ optional solution)
    cell_px, origin_x, origin_y = _compute_layout(maze)
    _draw_maze_grid(c, maze, cell_px, origin_x, origin_y)
    _draw_start_end_markers(c, maze, cell_px, origin_x, origin_y)

    if solution_path:
        _draw_solution_path_with_rows(
            c, solution_path, cell_px, origin_x, origin_y, maze.rows
        )
        # Re-draw markers on top of the solution line
        _draw_start_end_markers(c, maze, cell_px, origin_x, origin_y)

    # 4. footer
    _draw_footer(c, footer)
