"""
wordsearch/renderer.py
──────────────────────
ReportLab vector renderer for WordGrid objects matching the premium capsule-style layout.

Design constraints
──────────────────
▸ Answer Page: Found words highlighted with multi-colored pill/stadium capsules
  (rounded ends, distinct pastel colors, black outline around each capsule).
▸ Letters in the grid are printed in bold black text on top of the capsules.
▸ Word list at the bottom is enclosed in a double-line border box.
▸ In the Answer Page, each word in the list has a matching colored pill background.
▸ Grid outer frame is a clean solid vector rectangle.
"""

from __future__ import annotations

import io
import math
from typing import Dict, List, Optional, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas

from wordsearch.generator import WordGrid, Placement


# ── palette for word capsules ───────────────────────────────────────────────

PASTEL_PALETTE: List[colors.Color] = [
    colors.HexColor("#86EFAC"),  # Pastel Lime / Light Green
    colors.HexColor("#7DD3FC"),  # Sky Blue
    colors.HexColor("#F472B6"),  # Soft Pink / Magenta
    colors.HexColor("#FDE047"),  # Bright Yellow
    colors.HexColor("#C084FC"),  # Soft Purple / Lavender
    colors.HexColor("#CBD5E1"),  # Light Slate / Gray
    colors.HexColor("#FB923C"),  # Soft Orange / Peach
    colors.HexColor("#A7F3D0"),  # Mint Green
    colors.HexColor("#E9D5FF"),  # Light Violet
    colors.HexColor("#93C5FD"),  # Powder Blue
    colors.HexColor("#FCA5A5"),  # Soft Coral
    colors.HexColor("#FDE68A"),  # Warm Gold
]


# ── layout constants ─────────────────────────────────────────────────────────

_PAGE_W, _PAGE_H = A4
_MARGIN_SIDE     = 18 * mm
_MARGIN_TOP      = 22 * mm
_MARGIN_BOTTOM   = 16 * mm
_TITLE_SIZE      = 18
_FOOTER_SIZE     = 8
_FONT_BOLD       = "Helvetica-Bold"
_FONT_REGULAR    = "Helvetica"


# ── public API ────────────────────────────────────────────────────────────────

def build_puzzle_pdf(
    wg: WordGrid,
    title:  str = "Word Search",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """Render the word-search puzzle (no answers highlighted) to in-memory PDF."""
    buf = io.BytesIO()
    c   = rl_canvas.Canvas(buf, pagesize=A4)
    _draw_page(c, wg, title, footer, highlight=False)
    c.save()
    buf.seek(0)
    return buf


def build_answer_pdf(
    wg: WordGrid,
    title:  str = "Word Search — Answer Key",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """Render the word-search answer key with colored stadium/pill capsule highlights."""
    buf = io.BytesIO()
    c   = rl_canvas.Canvas(buf, pagesize=A4)
    _draw_page(c, wg, title, footer, highlight=True)
    c.save()
    buf.seek(0)
    return buf


# ── page composer ─────────────────────────────────────────────────────────────

def _draw_page(
    c:         rl_canvas.Canvas,
    wg:        WordGrid,
    title:     str,
    footer:    str,
    highlight: bool,
) -> None:
    # 1. Page background (clean white)
    c.setFillColor(colors.white)
    c.rect(0, 0, _PAGE_W, _PAGE_H, stroke=0, fill=1)

    # 2. Title
    _draw_title(c, title)

    # 3. Assign distinct color to each placement
    pl_colors: Dict[str, colors.Color] = {}
    for idx, pl in enumerate(wg.placements):
        pl_colors[pl.word] = PASTEL_PALETTE[idx % len(PASTEL_PALETTE)]

    # 4. Compute layout
    cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h = _compute_layout(wg)

    # 5. On Answer Page, draw capsules BEFORE drawing letters
    if highlight:
        _draw_capsule_highlights(c, wg, pl_colors, cell_px, grid_ox, grid_oy)

    # 6. Draw grid outer frame & letters (letters drawn on top of capsules)
    _draw_grid(c, wg, cell_px, grid_ox, grid_oy)

    # 7. Word list double-bordered box at bottom
    _draw_word_list_box(c, wg, pl_colors, highlight, box_ox, box_oy, box_w, box_h)

    # 8. Footer
    _draw_footer(c, footer)


# ── layout computation ────────────────────────────────────────────────────────

def _compute_layout(
    wg: WordGrid
) -> Tuple[float, float, float, float, float, float, float]:
    """
    Returns (cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h).
    """
    max_grid_w = _PAGE_W - 2 * _MARGIN_SIDE
    max_grid_h = 440.0   # available height for grid area

    cell_px = min(max_grid_w / wg.cols, max_grid_h / wg.rows)
    cell_px = max(12.0, (cell_px * 2) // 1 / 2)   # floor to 0.5pt, min 12pt

    grid_w = cell_px * wg.cols
    grid_h = cell_px * wg.rows

    grid_ox = (_PAGE_W - grid_w) / 2
    grid_oy = _PAGE_H - _MARGIN_TOP - _TITLE_SIZE - 20 - grid_h

    # Bottom word list box layout
    box_w  = grid_w
    box_ox = grid_ox

    avail_h = grid_oy - _MARGIN_BOTTOM - 20
    box_h  = max(70.0, min(140.0, avail_h))
    box_oy = grid_oy - 18 - box_h

    return cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h


# ── grid & letters drawing ────────────────────────────────────────────────────

def _draw_grid(
    c: rl_canvas.Canvas,
    wg: WordGrid,
    cell_px: float,
    ox: float, oy: float,
) -> None:
    """Draw outer border box and cell letters."""
    rows, cols = wg.rows, wg.cols
    grid_w = cell_px * cols
    grid_h = cell_px * rows

    font_size = max(8.0, cell_px * 0.58)

    # Letters — bold black text, centered in each cell
    c.setFillColor(colors.black)
    c.setFont(_FONT_BOLD, font_size)

    for row in range(rows):
        for col in range(cols):
            letter = wg.grid[row][col]
            cx = ox + (col + 0.5) * cell_px
            cy = oy + (rows - 1 - row + 0.5) * cell_px - font_size * 0.35
            c.drawCentredString(cx, cy, letter)

    # Outer border (clean thick black box frame)
    c.setStrokeColor(colors.black)
    c.setLineWidth(1.8)
    c.rect(ox, oy, grid_w, grid_h, stroke=1, fill=0)


# ── capsule highlights for answer page ────────────────────────────────────────

def _draw_capsule_highlights(
    c: rl_canvas.Canvas,
    wg: WordGrid,
    pl_colors: Dict[str, colors.Color],
    cell_px: float,
    ox: float, oy: float,
) -> None:
    """
    Draw stadium / pill capsule shapes around each found word.
    Black stroke outline + vibrant pastel color fill.
    """
    capsule_w = cell_px * 0.76

    for pl in wg.placements:
        p_color = pl_colors.get(pl.word, PASTEL_PALETTE[0])

        r1, c1 = pl.row, pl.col
        r2 = pl.row + (len(pl.word) - 1) * pl.dr
        c2 = pl.col + (len(pl.word) - 1) * pl.dc

        # Cell centers in ReportLab canvas coords
        x1 = ox + (c1 + 0.5) * cell_px
        y1 = oy + (wg.rows - 1 - r1 + 0.5) * cell_px

        x2 = ox + (c2 + 0.5) * cell_px
        y2 = oy + (wg.rows - 1 - r2 + 0.5) * cell_px

        # 1. Outer black capsule border
        c.saveState()
        c.setStrokeColor(colors.black)
        c.setLineWidth(capsule_w)
        c.setLineCap(1)  # round cap
        c.line(x1, y1, x2, y2)
        c.restoreState()

        # 2. Inner color fill capsule
        c.saveState()
        c.setStrokeColor(p_color)
        c.setLineWidth(capsule_w - 2.4)   # Leaves a crisp 1.2pt black outline
        c.setLineCap(1)  # round cap
        c.line(x1, y1, x2, y2)
        c.restoreState()


# ── word list box at bottom ───────────────────────────────────────────────────

def _draw_word_list_box(
    c: rl_canvas.Canvas,
    wg: WordGrid,
    pl_colors: Dict[str, colors.Color],
    highlight: bool,
    box_x: float,
    box_y: float,
    box_w: float,
    box_h: float,
) -> None:
    """
    Draw double-bordered word list container box at bottom.
    Words arranged in 3 or 4 columns.
    On Answer Page, each word has a colored pill background matching its grid capsule.
    """
    # Outer border box
    c.setStrokeColor(colors.black)
    c.setLineWidth(1.2)
    c.rect(box_x, box_y, box_w, box_h, stroke=1, fill=0)

    # Inner border box (double border effect)
    c.setLineWidth(0.6)
    c.rect(box_x + 2.5, box_y + 2.5, box_w - 5, box_h - 5, stroke=1, fill=0)

    words = wg.hidden_words
    if not words:
        return

    n_cols = 3 if len(words) <= 18 else 4
    n_rows = math.ceil(len(words) / n_cols)

    pad_x = 8.0
    pad_y = 6.0
    usable_w = box_w - 2 * pad_x
    usable_h = box_h - 2 * pad_y

    col_w = usable_w / n_cols
    row_h = usable_h / max(1, n_rows)

    pill_h = min(row_h - 3.5, 17.0)
    font_size = min(9.5, pill_h * 0.62)

    for idx, word in enumerate(words):
        col_idx = idx % n_cols
        row_idx = idx // n_cols

        wx = box_x + pad_x + col_idx * col_w + 3
        wy = box_y + box_h - pad_y - (row_idx + 0.5) * row_h - pill_h / 2
        pw = col_w - 6

        if highlight and word in pl_colors:
            p_color = pl_colors[word]
            # Colored background pill capsule
            c.saveState()
            c.setStrokeColor(colors.black)
            c.setLineWidth(0.8)
            c.setFillColor(p_color)
            c.roundRect(wx, wy, pw, pill_h, radius=pill_h / 2, stroke=1, fill=1)
            c.restoreState()

            # Word text in bold black
            c.setFillColor(colors.black)
            c.setFont(_FONT_BOLD, font_size)
            c.drawCentredString(wx + pw / 2, wy + (pill_h - font_size) / 2 + 1.5, word)
        else:
            # Puzzle Page (plain bold text)
            c.setFillColor(colors.black)
            c.setFont(_FONT_BOLD, font_size)
            c.drawCentredString(wx + pw / 2, wy + (pill_h - font_size) / 2 + 1.5, word)


# ── typography helpers ────────────────────────────────────────────────────────

def _draw_title(c: rl_canvas.Canvas, title: str) -> None:
    """Centred title — bold vector text."""
    c.setFillColor(colors.black)
    c.setFont(_FONT_BOLD, _TITLE_SIZE)
    c.drawCentredString(_PAGE_W / 2, _PAGE_H - _MARGIN_TOP, title)


def _draw_footer(c: rl_canvas.Canvas, footer: str) -> None:
    """Small footer with a separator line."""
    footer_y = _MARGIN_BOTTOM
    c.setStrokeColor(colors.black)
    c.setLineWidth(0.4)
    c.line(_MARGIN_SIDE, footer_y + 6, _PAGE_W - _MARGIN_SIDE, footer_y + 6)

    c.setFillColor(colors.black)
    c.setFont(_FONT_REGULAR, _FOOTER_SIZE)
    c.drawCentredString(_PAGE_W / 2, footer_y - 2, footer)
