"""
crossword/renderer.py
──────────────────────
ReportLab vector renderer for CrosswordGrid objects.
Generates print-ready black & white vector PDFs in memory.
"""

from __future__ import annotations

import io
import math
from typing import Dict, List, Optional, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas

from crossword.generator import CrosswordGrid, Placement

# ── layout constants ─────────────────────────────────────────────────────────

_PAGE_W, _PAGE_H = A4
_MARGIN_SIDE     = 18 * mm
_MARGIN_TOP      = 22 * mm
_MARGIN_BOTTOM   = 16 * mm
_TITLE_SIZE      = 18
_FOOTER_SIZE     = 8
_FONT_BOLD       = "Helvetica-Bold"
_FONT_REGULAR    = "Helvetica"


# ── public API ────────────────────────────────────────────────────────────────

def build_puzzle_pdf(
    cg: CrosswordGrid,
    title: str = "Crossword puzzle",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """Render the crossword puzzle (empty boxes with top-left numbers) to in-memory PDF."""
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)
    _draw_page(c, cg, title, footer, show_answers=False)
    c.save()
    buf.seek(0)
    return buf


def build_answer_pdf(
    cg: CrosswordGrid,
    title: str = "Crossword puzzle — Answer Key",
    footer: str = "Generated by Puzzle Generator",
) -> io.BytesIO:
    """Render the crossword answer key (filled letter boxes) to in-memory PDF."""
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)
    _draw_page(c, cg, title, footer, show_answers=True)
    c.save()
    buf.seek(0)
    return buf


# ── page composer ─────────────────────────────────────────────────────────────

def _draw_page(
    c: rl_canvas.Canvas,
    cg: CrosswordGrid,
    title: str,
    footer: str,
    show_answers: bool,
) -> None:
    # 1. Page background (clean white)
    c.setFillColor(colors.white)
    c.rect(0, 0, _PAGE_W, _PAGE_H, stroke=0, fill=1)

    # 2. Title
    _draw_title(c, title)

    # 3. Compute layout
    cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h = _compute_layout(cg)

    # 4. Draw grid boxes & numbers/letters
    _draw_grid(c, cg, cell_px, grid_ox, grid_oy, show_answers)

    # 5. Across & Down clues box
    _draw_clues_box(c, cg, box_ox, box_oy, box_w, box_h)

    # 6. Footer
    _draw_footer(c, footer)


# ── layout computation ────────────────────────────────────────────────────────

def _compute_layout(
    cg: CrosswordGrid,
) -> Tuple[float, float, float, float, float, float, float]:
    """
    Returns (cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h).
    """
    max_grid_w = _PAGE_W - 2 * _MARGIN_SIDE
    max_grid_h = 440.0

    cell_px = min(max_grid_w / cg.cols, max_grid_h / cg.rows)
    cell_px = max(14.0, min(36.0, (cell_px * 2) // 1 / 2))

    grid_w = cell_px * cg.cols
    grid_h = cell_px * cg.rows

    grid_ox = (_PAGE_W - grid_w) / 2
    grid_oy = _PAGE_H - _MARGIN_TOP - _TITLE_SIZE - 20 - grid_h

    box_w = max_grid_w
    box_ox = _MARGIN_SIDE

    avail_h = grid_oy - _MARGIN_BOTTOM - 20
    box_h = max(90.0, min(180.0, avail_h))
    box_oy = grid_oy - 18 - box_h

    return cell_px, grid_ox, grid_oy, box_ox, box_oy, box_w, box_h


# ── grid & boxes drawing ──────────────────────────────────────────────────────

def _draw_grid(
    c: rl_canvas.Canvas,
    cg: CrosswordGrid,
    cell_px: float,
    ox: float,
    oy: float,
    show_answers: bool,
) -> None:
    """Draw crossword active word boxes with top-left numbers and letters."""
    rows, cols = cg.rows, cg.cols
    num_font_size = max(5.5, min(8.5, cell_px * 0.30))
    letter_font_size = max(8.0, min(18.0, cell_px * 0.58))

    c.setStrokeColor(colors.black)
    c.setLineWidth(1.2)

    for r in range(rows):
        for col in range(cols):
            letter = cg.grid[r][col]
            if letter is None:
                continue  # Outside cell: leave blank/transparent

            # Canvas position for cell (ReportLab origin is bottom-left)
            x = ox + col * cell_px
            y = oy + (rows - 1 - r) * cell_px

            # Active square box
            c.setFillColor(colors.white)
            c.rect(x, y, cell_px, cell_px, stroke=1, fill=1)

            # Check for top-left clue number
            if (r, col) in cg.cell_numbers:
                num = cg.cell_numbers[(r, col)]
                c.setFillColor(colors.black)
                c.setFont(_FONT_BOLD, num_font_size)
                c.drawString(x + 2.0, y + cell_px - num_font_size - 1.0, str(num))

            # Draw answer letter if show_answers is True
            if show_answers and letter:
                c.setFillColor(colors.black)
                c.setFont(_FONT_BOLD, letter_font_size)
                cx = x + cell_px / 2.0
                cy = y + cell_px / 2.0 - letter_font_size * 0.35
                c.drawCentredString(cx, cy, letter)


# ── clues box drawing ─────────────────────────────────────────────────────────

def _draw_clues_box(
    c: rl_canvas.Canvas,
    cg: CrosswordGrid,
    box_x: float,
    box_y: float,
    box_w: float,
    box_h: float,
) -> None:
    """Draw Across & Down clues in a double-bordered container box."""
    # Outer border
    c.setStrokeColor(colors.black)
    c.setLineWidth(1.2)
    c.rect(box_x, box_y, box_w, box_h, stroke=1, fill=0)

    # Inner border
    c.setLineWidth(0.6)
    c.rect(box_x + 2.5, box_y + 2.5, box_w - 5, box_h - 5, stroke=1, fill=0)

    col_w = (box_w - 20) / 2
    x_across = box_x + 10
    x_down = box_x + 10 + col_w + 10

    y_top = box_y + box_h - 14

    # Headers
    c.setFillColor(colors.black)
    c.setFont(_FONT_BOLD, 10)
    c.drawString(x_across, y_top, "ACROSS")
    c.drawString(x_down, y_top, "DOWN")

    c.setLineWidth(0.6)
    c.line(x_across, y_top - 3, x_across + 60, y_top - 3)
    c.line(x_down, y_top - 3, x_down + 60, y_top - 3)

    # Render Across list
    _render_clue_list(c, cg.across_placements, x_across, y_top - 16, col_w, box_y + 6)

    # Render Down list
    _render_clue_list(c, cg.down_placements, x_down, y_top - 16, col_w, box_y + 6)


def _render_clue_list(
    c: rl_canvas.Canvas,
    placements: List[Placement],
    x: float,
    y_start: float,
    max_w: float,
    y_min: float,
) -> None:
    font_size = 8.0
    line_h = 10.5
    c.setFont(_FONT_REGULAR, font_size)

    curr_y = y_start
    for pl in placements:
        if curr_y - line_h < y_min:
            break

        clue_text = pl.clue if pl.clue != pl.word else pl.word
        text = f"{pl.number}. {clue_text}"

        # Truncate text if it exceeds column width
        if c.stringWidth(text, _FONT_REGULAR, font_size) > max_w:
            while len(text) > 4 and c.stringWidth(text + "…", _FONT_REGULAR, font_size) > max_w:
                text = text[:-1]
            text += "…"

        c.drawString(x, curr_y, text)
        curr_y -= line_h


# ── typography helpers ────────────────────────────────────────────────────────

def _draw_title(c: rl_canvas.Canvas, title: str) -> None:
    """Centred title — bold vector text."""
    c.setFillColor(colors.black)
    c.setFont(_FONT_BOLD, _TITLE_SIZE)
    c.drawCentredString(_PAGE_W / 2, _PAGE_H - _MARGIN_TOP, title)


def _draw_footer(c: rl_canvas.Canvas, footer: str) -> None:
    """Small footer with a separator line."""
    footer_y = _MARGIN_BOTTOM
    c.setStrokeColor(colors.black)
    c.setLineWidth(0.4)
    c.line(_MARGIN_SIDE, footer_y + 6, _PAGE_W - _MARGIN_SIDE, footer_y + 6)

    c.setFillColor(colors.black)
    c.setFont(_FONT_REGULAR, _FOOTER_SIZE)
    c.drawCentredString(_PAGE_W / 2, footer_y - 2, footer)
